import type { Metadata } from "next";
import { Anton_SC } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Footer from '@/Components/Footer';
import NavBar from "@/Components/NavBar/NavBar";

// Configuração das fontes online
const antonSC = Anton_SC({
  weight: "400",
  variable: "--font-anton_sc",
  subsets: ["latin"],
});

// COnfiguração de fonte local
const openDyslexic = localFont({
  src: [
    {
      path: "../../public/open_dyslexic/OpenDyslexic-Regular.otf",
      weight: "400",
      style: "normal"
    }
  ],
  variable: "--font-open-dyslexic"
});

// Metadata da aplicação
export const metadata: Metadata = {
  title: "AccessGame",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 return (
    <html lang="en">
      <body
        className={`${antonSC.variable} ${openDyslexic.variable} flex flex-col min-h-screen bg-[#0f0a1b]`}
      >
        <NavBar />
        <main className="grow">
          {children}
        </main>
        
        <Footer />
      </body>
    </html>
  );
}
